# Generated by Django 6.0.4 on 2026-05-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_trial', models.BooleanField(default=False, help_text='Whether this video is available for trial viewing')),
                ('trial_duration', models.PositiveIntegerField(default=300, help_text='Trial duration in seconds (default 5 minutes)')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('enrolled', 'Enrolled Users Only'), ('premium', 'Premium Users Only')], default='enrolled', help_text='Who can access this video', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
